#!/usr/bin/env bash
set -e
: ${CXX:="g++"}
echo "Negative tests using ${CXX}"
cases=$(cat forward_to_member_test.cpp | grep INVALID | wc -l)
for i in $(seq $cases);
do
    filename=$(mktemp --suffix=".cpp")
    cat forward_to_member_test.cpp | awk "{if(match(\$0, /INVALID/)) count++; if(count==$i){ gsub(\"//INVALID\",\"         \",\$0); print \$0; } else { print \$0; }}" > $filename
    echo Case $i of $cases
    ${CXX} -std=c++11 -I. -Wall -Wextra -Werror $filename > /dev/null 2>&1 && echo ERROR $(cat forward_to_member_test.cpp | grep INVALID | head -n $i | tail -1) && exit 1
done
exit 0
